# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 10:26
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('web_address', models.URLField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('misc1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misc2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misc3', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misc4', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misc5', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misc6', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misc7', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misc8', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misc9', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misc10', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misc11', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misc12', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misc13', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misc14', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misc15', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misc16', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misc17', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misc18', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misc19', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misc20', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misc21', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misc22', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misc23', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misc24', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misc25', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misc26', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misc27', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misc28', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misc29', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('countries_served', models.ManyToManyField(to='markets2.Country')),
            ],
            options={
                'ordering': ('country',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets2.Region'),
        ),
    ]
