# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('parent_company_name', models.CharField(blank=True, max_length=200)),
                ('goods_sold', models.TextField(blank=True)),
                ('brand_domestic', models.NullBooleanField()),
                ('brand_international', models.NullBooleanField()),
                ('brand_own', models.NullBooleanField()),
                ('volume_turnover', models.BigIntegerField(null=True)),
                ('volume_turnover_date', models.DateField(null=True)),
                ('turnover_currency_rate', models.DecimalField(decimal_places=5, max_digits=20, null=True)),
                ('volume_turnover_gbp', models.BigIntegerField(null=True)),
                ('turnover_conversion_date', models.DateField(null=True)),
                ('platform', models.CharField(blank=True, choices=[('0', 'B2B'), ('1', 'B2C')], max_length=1)),
                ('date_established', models.DateField(null=True)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_position', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=200)),
                ('contact_address', models.TextField(blank=True)),
                ('contact_other', models.TextField(blank=True)),
                ('strategy_recent_investments', models.TextField(blank=True)),
                ('comments_notes', models.TextField(blank=True)),
                ('sources', models.TextField(blank=True)),
                ('seller_application_process', models.TextField(blank=True)),
                ('registration_fee', models.IntegerField(null=True)),
                ('subscription_fee', models.IntegerField(null=True)),
                ('referral_fee', models.IntegerField(null=True)),
                ('additional_operating_costs', models.IntegerField(null=True)),
                ('shipping_fulfillment_details', models.TextField(blank=True)),
                ('online_marketing', models.TextField(blank=True)),
                ('payment_credit_card', models.NullBooleanField()),
                ('payment_debit_card', models.NullBooleanField()),
                ('payment_cod', models.NullBooleanField()),
                ('payment_bank_transfer', models.NullBooleanField()),
                ('payment_pay_pal', models.NullBooleanField()),
                ('payment_other', models.TextField(blank=True)),
                ('listing_english', models.NullBooleanField()),
                ('listing_local', models.NullBooleanField()),
                ('logistic_full', models.NullBooleanField()),
                ('logistic_partial', models.NullBooleanField()),
                ('logistic_diy', models.NullBooleanField()),
                ('position_premium', models.NullBooleanField()),
                ('position_midpoint', models.NullBooleanField()),
                ('position_discount', models.NullBooleanField()),
            ],
            options={
                'ordering': ('country',),
            },
        ),
    ]
