# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_auto_20160714_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='market',
            name='product_categories',
        ),
        migrations.AddField(
            model_name='market',
            name='product_categories',
            field=models.ManyToManyField(to='markets.ProductCategory'),
        ),
    ]
