# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_auto_20160715_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='buyers_customer_service',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='competitor_comparison',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='contact_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='customization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='fee_pricing_structure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='feedback_system',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='logistics_structure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='market',
            name='merchandising_offer_cost',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='payment_methods',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='payment_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='product_visibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='seller_support_structure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='shop_analytics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='translation_services',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='ukti_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='web_traffic_to_bounce',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='web_traffic_to_site',
            field=models.TextField(blank=True, null=True),
        ),
    ]
