# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 09:58
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0010_auto_20160722_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='product_promotion_options',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='social_media_integration',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
