# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='platform_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
