# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets3', '0002_market_platform_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='local_customer_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='market',
            name='product_type',
            field=models.CharField(blank=True, choices=[('0', 'Luxury'), ('1', 'Mid rage'), ('2', 'Discount')],
                                   max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='logistics_structure',
            field=models.CharField(blank=True, choices=[('0', 'Dropshipping'), ('1', 'Warehousing')],
                                   max_length=1, null=True),
        ),
    ]
