# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets3', '0006_auto_20160803_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldMarket',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'Market - deprecated',
                'verbose_name_plural': 'Markets - deprecated',
            },
            bases=('markets3.market',),
        ),
        migrations.AddField(
            model_name='market',
            name='web_traffic',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
