# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 11:32
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets1', '0003_auto_20160801_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
